### ISSUE TITLE
errors while compiling

### ISSUE THREAD

**Issue by lshhsl** [wichtounet/dll#10]
I compile the dll on Mac with clang-900.0.39.2,  but I get the following errors:

dll/etl/include/etl/impl/std/fft.hpp:638:22: error: use of undeclared identifier 'M_PIl'; did you mean 'P_PID'?
dll/etl/include/etl/op/unary/exp.hpp:62:19: error: no member named 'exp' in 'etl::no_vec'
dll/etl/include/etl/op/unary/log.hpp:62:19: error: no member named 'log' in 'etl::no_vec'
dll/etl/include/etl/expr/unary_expr.hpp:169:34: error: no matching member function for call to 'load'

any solutions?

**Comment by wichtounet** [comment]
Hello, 

I never tried to compile on Mac, but it should work with a recent version on clang. It seems to me that clang-900 is the clang 4.0 version, which should work with the latest version of DLL. 

Can you give me the full compiler error ? And can you give me the full options for compilation ?

Given the second and third errors, it seems to me that you try to use vectorizations but that you are not compiling with vectorization support (hence the no_vec). 

Thanks

Baptiste

**Comment by wichtounet** [comment]
Since there are no answers, I'm considering it fixed. Don't hesitate to open the issue again if you still have issues.
