### ISSUE TITLE
Build issue on g++ 7.3.0

### ISSUE THREAD

**Issue by chrispugmire** [wichtounet/dll#12]
Build issue?  Any advice appreciated, thanks.  

```
root@mail:~/dll/dll# make
-e \x1b[31;01m[release_debug]\x1b[0m Compile \x1b[35;01mprocessor/src/processor.cpp\x1b[0m
In file included from etl/include/etl/vectorization.hpp:59:0,
                 from etl/include/etl/etl.hpp:29,
                 from include/dll/rbm/dyn_rbm_impl.hpp:10,
                 from include/dll/rbm/dyn_rbm.hpp:10,
                 from include/dll/rbm/rbm.hpp:16,
                 from include/dll/processor/processor.hpp:20,
                 from processor/include/parse_utils.hpp:16,
                 from processor/src/processor.cpp:20:
etl/include/etl/avx512_vectorization.hpp:504:15: error: explicit specialization in non-namespace scope ‘struct etl::avx512_vec’
     template <>
               ^
etl/include/etl/avx512_vectorization.hpp:505:56: error: template-id ‘mul<true>’ in declaration of primary template
     ETL_INLINE_VEC_512 mul<true>(__m512 lhs, __m512 rhs) {
                                                        ^
etl/include/etl/avx512_vectorization.hpp:514:25: error: too many template-parameter-lists
     ETL_INLINE_VEC_512D mul(__m512d lhs, __m512d rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:521:15: error: explicit specialization in non-namespace scope ‘struct etl::avx512_vec’
     template <>
               ^
etl/include/etl/avx512_vectorization.hpp:522:59: error: template-id ‘mul<true>’ in declaration of primary template
     ETL_INLINE_VEC_512D mul<true>(__m512d lhs, __m512d rhs) {
                                                           ^
etl/include/etl/avx512_vectorization.hpp:531:24: error: too many template-parameter-lists
     ETL_INLINE_VEC_512 div(__m512 lhs, __m512 rhs) {
                        ^~~
etl/include/etl/avx512_vectorization.hpp:538:15: error: explicit specialization in non-namespace scope ‘struct etl::avx512_vec’
     template <>
               ^
etl/include/etl/avx512_vectorization.hpp:539:24: error: ‘__always_inline__’ attribute ignored [-Werror=attributes]
     ETL_INLINE_VEC_512 div<true>(__m512 lhs, __m512 rhs) {
                        ^~~
etl/include/etl/avx512_vectorization.hpp:539:24: error: ‘__gnu_inline__’ attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:539:24: error: ‘__artificial__’ attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:539:24: error: expected ‘;’ at end of member declaration
etl/include/etl/avx512_vectorization.hpp:539:27: error: expected unqualified-id before ‘<’ token
     ETL_INLINE_VEC_512 div<true>(__m512 lhs, __m512 rhs) {
                           ^
etl/include/etl/avx512_vectorization.hpp:548:25: error: too many template-parameter-lists
     ETL_INLINE_VEC_512D div(__m512d lhs, __m512d rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:555:15: error: explicit specialization in non-namespace scope ‘struct etl::avx512_vec’
     template <>
               ^
etl/include/etl/avx512_vectorization.hpp:556:25: error: ‘__always_inline__’ attribute ignored [-Werror=attributes]
     ETL_INLINE_VEC_512D div<true>(__m512d lhs, __m512d rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:556:25: error: ‘__gnu_inline__’ attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:556:25: error: ‘__artificial__’ attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:556:25: error: expected ‘;’ at end of member declaration
etl/include/etl/avx512_vectorization.hpp:556:25: error: redeclaration of ‘__m512d etl::avx512_vec::div’
etl/include/etl/avx512_vectorization.hpp:539:24: note: previous declaration ‘__m512 etl::avx512_vec::div’
     ETL_INLINE_VEC_512 div<true>(__m512 lhs, __m512 rhs) {
                        ^~~
etl/include/etl/avx512_vectorization.hpp:556:28: error: expected unqualified-id before ‘<’ token
     ETL_INLINE_VEC_512D div<true>(__m512d lhs, __m512d rhs) {
                            ^
etl/include/etl/avx512_vectorization.hpp: In static member function ‘static __m512 etl::avx512_vec::mul(__m512, __m512)’:
etl/include/etl/avx512_vectorization.hpp:505:53: error: unused parameter ‘rhs’  -Werror=unused-parameter]
     ETL_INLINE_VEC_512 mul<true>(__m512 lhs, __m512 rhs) {
                                                     ^~~
etl/include/etl/avx512_vectorization.hpp: In static member function ‘static __m512d etl::avx512_vec::mul(__m512d, __m512d)’:
etl/include/etl/avx512_vectorization.hpp:522:56: error: unused parameter ‘rhs’  -Werror=unused-parameter]
     ETL_INLINE_VEC_512D mul<true>(__m512d lhs, __m512d rhs) {
                                                        ^~~
etl/include/etl/avx512_vectorization.hpp: At global scope:
etl/include/etl/avx512_vectorization.hpp:634:1: error: ‘ETL_OUT_VEC_512’ does not name a type; did you mean ‘ETL_OUT_VEC_512D’?
 ETL_OUT_VEC_512 avx512_vec::mul<true>(__m512 lhs, __m512 rhs) {
 ^~~~~~~~~~~~~~~
 ETL_OUT_VEC_512D
etl/include/etl/avx512_vectorization.hpp:643:18: error: template-id ‘mul<true>’ for ‘__m512d etl::avx512_vec::mul(__m512d, __m512d)’ does not match any template declaration
 ETL_OUT_VEC_512D avx512_vec::mul<true>(__m512d lhs, __m512d rhs) {
                  ^~~~~~~~~~
etl/include/etl/avx512_vectorization.hpp:522:25: note: candidates are: static __m512d etl::avx512_vec::mul(__m512d, __m512d)
     ETL_INLINE_VEC_512D mul<true>(__m512d lhs, __m512d rhs) {
                         ^~~~~~~~~
etl/include/etl/avx512_vectorization.hpp:505:24: note:                 static __m512 etl::avx512_vec::mul(__m512, __m512)
     ETL_INLINE_VEC_512 mul<true>(__m512 lhs, __m512 rhs) {
                        ^~~~~~~~~
etl/include/etl/avx512_vectorization.hpp:497:24: note:                 template<bool Complex> static __m512 etl::avx512_vec::mul(__m512, __m512)
     ETL_INLINE_VEC_512 mul(__m512 lhs, __m512 rhs) {
                        ^~~
etl/include/etl/avx512_vectorization.hpp:652:1: error: ‘ETL_OUT_VEC_512’ does not name a type; did you mean ‘ETL_OUT_VEC_512D’?
 ETL_OUT_VEC_512 avx512_vec::div<true>(__m512 lhs, __m512 rhs) {
 ^~~~~~~~~~~~~~~
 ETL_OUT_VEC_512D
etl/include/etl/avx512_vectorization.hpp:661:33: error: expected initializer before ‘<’ token
 ETL_OUT_VEC_512D avx512_vec::div<true>(__m512d lhs, __m512d rhs) {
                                 ^
cc1plus: all warnings being treated as errors
Makefile:172: recipe for target 'release_debug/processor/src/processor.cpp.o' failed
make: *** [release_debug/processor/src/processor.cpp.o] Error 1
```

```
root@mail:~/dll/dll# g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by wichtounet** [comment]
Hello, 

It seems your processor has support for AVX512F. I prepared the code for this but I was never able to test since I never add a processor to test it :(

Can you try this command:

`CXXF_FLAGS="-mno-avx512f" make`

?

It should disable the AVX512F that is broken.

**Comment by chrispugmire** [comment]
Sorry that didn't help... log below..

ChrisP.



root@mail:~/dll/dll# CXXF_FLAGS="-mno-avx512f" make
-e \x1b[31;01m[release_debug]\x1b[0m Compile 
\x1b[35;01mprocessor/src/processor.cpp\x1b[0m
In file included from etl/include/etl/vectorization.hpp:59:0,
                  from etl/include/etl/etl.hpp:29,
                  from include/dll/rbm/dyn_rbm_impl.hpp:10,
                  from include/dll/rbm/dyn_rbm.hpp:10,
                  from include/dll/rbm/rbm.hpp:16,
                  from include/dll/processor/processor.hpp:20,
                  from processor/include/parse_utils.hpp:16,
                  from processor/src/processor.cpp:20:
etl/include/etl/avx512_vectorization.hpp:504:15: error: explicit 
specialization in non-namespace scope ‘struct etl::avx512_vec’
      template <>
                ^
etl/include/etl/avx512_vectorization.hpp:505:56: error: template-id 
‘mul<true>’ in declaration of primary template
      ETL_INLINE_VEC_512 mul<true>(__m512 lhs, __m512 rhs) {
                                                         ^
etl/include/etl/avx512_vectorization.hpp:514:25: error: too many 
template-parameter-lists
      ETL_INLINE_VEC_512D mul(__m512d lhs, __m512d rhs) {
                          ^~~
etl/include/etl/avx512_vectorization.hpp:521:15: error: explicit 
specialization in non-namespace scope ‘struct etl::avx512_vec’
      template <>
                ^
etl/include/etl/avx512_vectorization.hpp:522:59: error: template-id 
‘mul<true>’ in declaration of primary template
      ETL_INLINE_VEC_512D mul<true>(__m512d lhs, __m512d rhs) {
                                                            ^
etl/include/etl/avx512_vectorization.hpp:531:24: error: too many 
template-parameter-lists
      ETL_INLINE_VEC_512 div(__m512 lhs, __m512 rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:538:15: error: explicit 
specialization in non-namespace scope ‘struct etl::avx512_vec’
      template <>
                ^
etl/include/etl/avx512_vectorization.hpp:539:24: error: 
‘__always_inline__’ attribute ignored [-Werror=attributes]
      ETL_INLINE_VEC_512 div<true>(__m512 lhs, __m512 rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:539:24: error: ‘__gnu_inline__’ 
attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:539:24: error: ‘__artificial__’ 
attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:539:24: error: expected ‘;’ at 
end of member declaration
etl/include/etl/avx512_vectorization.hpp:539:27: error: expected 
unqualified-id before ‘<’ token
      ETL_INLINE_VEC_512 div<true>(__m512 lhs, __m512 rhs) {
                            ^
etl/include/etl/avx512_vectorization.hpp:548:25: error: too many 
template-parameter-lists
      ETL_INLINE_VEC_512D div(__m512d lhs, __m512d rhs) {
                          ^~~
etl/include/etl/avx512_vectorization.hpp:555:15: error: explicit 
specialization in non-namespace scope ‘struct etl::avx512_vec’
      template <>
                ^
etl/include/etl/avx512_vectorization.hpp:556:25: error: 
‘__always_inline__’ attribute ignored [-Werror=attributes]
      ETL_INLINE_VEC_512D div<true>(__m512d lhs, __m512d rhs) {
                          ^~~
etl/include/etl/avx512_vectorization.hpp:556:25: error: ‘__gnu_inline__’ 
attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:556:25: error: ‘__artificial__’ 
attribute ignored [-Werror=attributes]
etl/include/etl/avx512_vectorization.hpp:556:25: error: expected ‘;’ at 
end of member declaration
etl/include/etl/avx512_vectorization.hpp:556:25: error: redeclaration of 
‘__m512d etl::avx512_vec::div’
etl/include/etl/avx512_vectorization.hpp:539:24: note: previous 
declaration ‘__m512 etl::avx512_vec::div’
      ETL_INLINE_VEC_512 div<true>(__m512 lhs, __m512 rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:556:28: error: expected 
unqualified-id before ‘<’ token
      ETL_INLINE_VEC_512D div<true>(__m512d lhs, __m512d rhs) {
                             ^
etl/include/etl/avx512_vectorization.hpp: In static member function 
‘static __m512 etl::avx512_vec::mul(__m512, __m512)’:
etl/include/etl/avx512_vectorization.hpp:505:53: error: unused parameter 
‘rhs’  -Werror=unused-parameter]
      ETL_INLINE_VEC_512 mul<true>(__m512 lhs, __m512 rhs) {
                                                      ^~~
etl/include/etl/avx512_vectorization.hpp: In static member function 
‘static __m512d etl::avx512_vec::mul(__m512d, __m512d)’:
etl/include/etl/avx512_vectorization.hpp:522:56: error: unused parameter 
‘rhs’  -Werror=unused-parameter]
      ETL_INLINE_VEC_512D mul<true>(__m512d lhs, __m512d rhs) {
                                                         ^~~
etl/include/etl/avx512_vectorization.hpp: At global scope:
etl/include/etl/avx512_vectorization.hpp:634:1: error: ‘ETL_OUT_VEC_512’ 
does not name a type; did you mean ‘ETL_OUT_VEC_512D’?
  ETL_OUT_VEC_512 avx512_vec::mul<true>(__m512 lhs, __m512 rhs) {
  ^~~~~~~~~~~~~~~
  ETL_OUT_VEC_512D
etl/include/etl/avx512_vectorization.hpp:643:18: error: template-id 
‘mul<true>’ for ‘__m512d etl::avx512_vec::mul(__m512d, __m512d)’ does 
not match any template declaration
  ETL_OUT_VEC_512D avx512_vec::mul<true>(__m512d lhs, __m512d rhs) {
                   ^~~~~~~~~~
etl/include/etl/avx512_vectorization.hpp:522:25: note: candidates are: 
static __m512d etl::avx512_vec::mul(__m512d, __m512d)
      ETL_INLINE_VEC_512D mul<true>(__m512d lhs, __m512d rhs) {
                          ^~~~~~~~~
etl/include/etl/avx512_vectorization.hpp:505:24: note:                 
static __m512 etl::avx512_vec::mul(__m512, __m512)
      ETL_INLINE_VEC_512 mul<true>(__m512 lhs, __m512 rhs) {
                         ^~~~~~~~~
etl/include/etl/avx512_vectorization.hpp:497:24: note:                 
template<bool Complex> static __m512 etl::avx512_vec::mul(__m512, __m512)
      ETL_INLINE_VEC_512 mul(__m512 lhs, __m512 rhs) {
                         ^~~
etl/include/etl/avx512_vectorization.hpp:652:1: error: ‘ETL_OUT_VEC_512’ 
does not name a type; did you mean ‘ETL_OUT_VEC_512D’?
  ETL_OUT_VEC_512 avx512_vec::div<true>(__m512 lhs, __m512 rhs) {
  ^~~~~~~~~~~~~~~
  ETL_OUT_VEC_512D
etl/include/etl/avx512_vectorization.hpp:661:33: error: expected 
initializer before ‘<’ token
  ETL_OUT_VEC_512D avx512_vec::div<true>(__m512d lhs, __m512d rhs) {
                                  ^
cc1plus: all warnings being treated as errors
Makefile:172: recipe for target 
'release_debug/processor/src/processor.cpp.o' failed
make: *** [release_debug/processor/src/processor.cpp.o] Error 1

**Comment by wichtounet** [comment]
Hi, 

I just realized that the command I gave you was wrong :(
It took me a while to realize that, sorry. I do not really focus about this project anymore. 

If you still care about that, can you try:

`CXX_FLAGS="-mno-avx512f" make`

?

**Comment by chrispugmire** [comment]
Thanks I appreciate your taking the time to send a correction.
      Chrisp.
