### ISSUE TITLE
Please fix the folder name.

### ISSUE THREAD

**Issue by kjleeic** [wichtounet/dll#2]
In the most recent release, @ is included in the folder name.
: etl -> etl @ f1e4c22

Because of this, I can not download the folder in Ubuntu.

Please fix the folder name.

**Comment by wichtounet** [comment]
That's only the display of Github, this has nothing to do with the real name of the folder. The name of the folder is still etl. 

If you clone the repository, the folder is called etl.

**Comment by kjleeic** [comment]
It doesn't work in my computer regardless OS: window, mac, ubuntu.

I clone the repository, using below command
git clone https://github.com/wichtounet/dll.git

but, some folder(etl, catch, cifar, mnist) are empty.

**Comment by wichtounet** [comment]
You need to clone the submodules as well: 

git clone --recursive https://github.com/wichtounet/dll.git

It was not mentioned in the Readme, I just added a note to the Readme now. Sorry about that.

**Comment by wichtounet** [comment]
Seems to be resolved. Let me know if you want to reopen.
