### ISSUE TITLE
AutoEncoder Example doesn't  be compiled.

### ISSUE THREAD

**Issue by kjleeic** [wichtounet/dll#5]
Hi!

Thanks to you, I have made the build environment and have compiled some examples (mnist_cnn.cpp, mnist_mlp.cpp).

However, auto encoder examples (mnist_ae.cpp, mnist_deep_ae.cpp) doesn't be compiled with following errors:

> clang++-3.9 -std=c++1y -I/home/kjlee/lib/dll/include -I/home/kjlee/lib/dll/Catch/include -I/home/kjlee/lib/dll/etl/include -I/home/kjlee/lib/dll/etl/lib/include -I/home/kjlee/lib/dll/mnist/include -I/home/kjlee/lib/dll/cifar-10/include -I/home/kjlee/lib/dll/nice-svm/include -lpthread  mnist_ae.cpp
> In file included from mnist_ae.cpp:10:
> In file included from /home/kjlee/lib/dll/include/dll/datasets.hpp:143:
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:98:88: error: missing default argument on parameter 'parameters'
> auto make_mnist_ae_generator_train(size_t start = 0, size_t limit = 0, Parameters&&... parameters){
>                                                                                        ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:140:9: note: in instantiation of function template specialization 'dll::make_mnist_ae_generator_train<dll::batch_size<256>, dll::scale_pre<255> >' requested
>       here
>         make_mnist_ae_generator_train(0UL, 60000UL, std::forward<Parameters>(parameters)...),
>         ^
> mnist_ae.cpp:17:25: note: in instantiation of function template specialization 'dll::make_mnist_ae_dataset<dll::batch_size<256>, dll::scale_pre<255> >' requested here
>     auto dataset = dll::make_mnist_ae_dataset(dll::batch_size<256>{}, dll::scale_pre<255>{});
>                         ^
> In file included from mnist_ae.cpp:10:
> In file included from /home/kjlee/lib/dll/include/dll/datasets.hpp:143:
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:98:88: error: missing default argument on parameter 'parameters'
> auto make_mnist_ae_generator_train(size_t start = 0, size_t limit = 0, Parameters&&... parameters){
>                                                                                        ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:98:88: error: missing default argument on parameter 'parameters'
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:99:12: note: in instantiation of function template specialization 'dll::make_mnist_ae_generator_train<unsigned long &, dll::batch_size<256>,
>       dll::scale_pre<255> >' requested here
>     return make_mnist_ae_generator_train("mnist", start, limit, std::forward<Parameters>(parameters)...);
>            ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:140:9: note: in instantiation of function template specialization 'dll::make_mnist_ae_generator_train<dll::batch_size<256>, dll::scale_pre<255> >' requested
>       here
>         make_mnist_ae_generator_train(0UL, 60000UL, std::forward<Parameters>(parameters)...),
>         ^
> mnist_ae.cpp:17:25: note: in instantiation of function template specialization 'dll::make_mnist_ae_dataset<dll::batch_size<256>, dll::scale_pre<255> >' requested here
>     auto dataset = dll::make_mnist_ae_dataset(dll::batch_size<256>{}, dll::scale_pre<255>{});
>                         ^
> In file included from mnist_ae.cpp:10:
> In file included from /home/kjlee/lib/dll/include/dll/datasets.hpp:143:
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:98:88: error: missing default argument on parameter 'parameters'
> auto make_mnist_ae_generator_train(size_t start = 0, size_t limit = 0, Parameters&&... parameters){
>                                                                                        ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:98:88: error: missing default argument on parameter 'parameters'
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:112:87: error: missing default argument on parameter 'parameters'
> auto make_mnist_ae_generator_test(size_t start = 0, size_t limit = 0, Parameters&&... parameters){
>                                                                                       ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:141:9: note: in instantiation of function template specialization 'dll::make_mnist_ae_generator_test<dll::batch_size<256>, dll::scale_pre<255> >' requested
>       here
>         make_mnist_ae_generator_test(0UL, 10000UL, std::forward<Parameters>(parameters)...));
>         ^
> mnist_ae.cpp:17:25: note: in instantiation of function template specialization 'dll::make_mnist_ae_dataset<dll::batch_size<256>, dll::scale_pre<255> >' requested here
>     auto dataset = dll::make_mnist_ae_dataset(dll::batch_size<256>{}, dll::scale_pre<255>{});
>                         ^
> In file included from mnist_ae.cpp:10:
> In file included from /home/kjlee/lib/dll/include/dll/datasets.hpp:143:
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:112:87: error: missing default argument on parameter 'parameters'
> auto make_mnist_ae_generator_test(size_t start = 0, size_t limit = 0, Parameters&&... parameters){
>                                                                                       ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:112:87: error: missing default argument on parameter 'parameters'
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:113:12: note: in instantiation of function template specialization 'dll::make_mnist_ae_generator_test<unsigned long &, dll::batch_size<256>,
>       dll::scale_pre<255> >' requested here
>     return make_mnist_ae_generator_test("mnist", start, limit, std::forward<Parameters>(parameters)...);
>            ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:141:9: note: in instantiation of function template specialization 'dll::make_mnist_ae_generator_test<dll::batch_size<256>, dll::scale_pre<255> >' requested
>       here
>         make_mnist_ae_generator_test(0UL, 10000UL, std::forward<Parameters>(parameters)...));
>         ^
> mnist_ae.cpp:17:25: note: in instantiation of function template specialization 'dll::make_mnist_ae_dataset<dll::batch_size<256>, dll::scale_pre<255> >' requested here
>     auto dataset = dll::make_mnist_ae_dataset(dll::batch_size<256>{}, dll::scale_pre<255>{});
>                         ^
> In file included from mnist_ae.cpp:10:
> In file included from /home/kjlee/lib/dll/include/dll/datasets.hpp:143:
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:112:87: error: missing default argument on parameter 'parameters'
> auto make_mnist_ae_generator_test(size_t start = 0, size_t limit = 0, Parameters&&... parameters){
>                                                                                       ^
> /home/kjlee/lib/dll/include/dll/datasets/mnist_ae.hpp:112:87: error: missing default argument on parameter 'parameters'
> 10 errors generated.
> 

Please help me.

**Comment by wichtounet** [comment]
Hi, 

You're right, it was compiling with G++ but not clang++, this should be fixed now with 45ca13ab666e41d56c3dc18ee9db7de3a58fbe59

You can update DLL and try if it works. 

Sorry about that :(

Baptiste

**Comment by kjleeic** [comment]
Thank you. now it works!
