### ISSUE TITLE
ETL_CUBLAS_MODE & ETL_CUDNN_MODE

### ISSUE THREAD

**Issue by kjleeic** [wichtounet/dll#6]
![image](https://user-images.githubusercontent.com/26650198/31927422-e6b50f0c-b8ce-11e7-9dcf-214b3855260a.png)

I want to use DLL with GPU.
So I install cuda-toolkit 7.5 & cudnn (corresponding version of cuda-toolkit 7.5).
I write down my Makefile as shown above (-DETL_CUBLAS_MODE -DETL_CUDNN_MODE).

However,
It make error when I execute **make ae**:

> kjlee@ubuntu:~/Study/DLL/1_test$ **make ae**
> clang++-3.9 -std=c++14 -I/home/kjlee/lib/dll/include -I/home/kjlee/lib/dll/Catch/include -I/home/kjlee/lib/dll/etl/include -I/home/kjlee/lib/dll/etl/lib/include -I/home/kjlee/lib/dll/mnist/include -I/home/kjlee/lib/dll/cifar-10/include -I/home/kjlee/lib/dll/nice-svm/include -I/home/kjlee/lib/cuda-7.5/include -lpthread -L/home/kjlee/lib/cuda-7.5/lib -L/home/kjlee/lib/cuda-7.5/lib64 -lcublas -lcudart -DETL_PARALLEL -DETL_VECTORIZE_FULL mnist_ae.cpp
> /usr/bin/ld: skipping incompatible /home/kjlee/lib/cuda-7.5/lib/libcudart.so when searching for -lcudart
> kjlee@ubuntu:~/Study/DLL/1_test$ vi Makefile 
> kjlee@ubuntu:~/Study/DLL/1_test$ make ae
> clang++-3.9 -std=c++14 -I/home/kjlee/lib/dll/include -I/home/kjlee/lib/dll/Catch/include -I/home/kjlee/lib/dll/etl/include -I/home/kjlee/lib/dll/etl/lib/include -I/home/kjlee/lib/dll/mnist/include -I/home/kjlee/lib/dll/cifar-10/include -I/home/kjlee/lib/dll/nice-svm/include -I/home/kjlee/lib/cuda-7.5/include -lpthread -L/home/kjlee/lib/cuda-7.5/lib -L/home/kjlee/lib/cuda-7.5/lib64 -lcublas -lcudart -DETL_PARALLEL -DETL_VECTORIZE_FULL -DETL_CUBLAS_MODE -DETL_CUDNN_MODE mnist_ae.cpp
> /usr/bin/ld: skipping incompatible /home/kjlee/lib/cuda-7.5/lib/libcudart.so when searching for -lcudart
> /tmp/mnist_ae-95cfa4.o: In function `void etl::impl::cudnn::bias_add_2d<etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 1ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 1ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x5b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x9a): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x241): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x286): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x479): undefined reference to `cudnnTransformTensor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x4be): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x704): undefined reference to `cudnnDestroyTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_[_ZN3etl4impl5cudnn11bias_add_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERKNS3_IfLS4_0ELm1EEERS5_EEvOT_OT0_OT1_]+0x749): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `etl::impl::cudnn::cudnn_wrapper<cudnnTensorStruct*>::~cudnn_wrapper()':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13cudnn_wrapperIP17cudnnTensorStructED2Ev[_ZN3etl4impl5cudnn13cudnn_wrapperIP17cudnnTensorStructED2Ev]+0x29): undefined reference to `cudnnDestroyTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13cudnn_wrapperIP17cudnnTensorStructED2Ev[_ZN3etl4impl5cudnn13cudnn_wrapperIP17cudnnTensorStructED2Ev]+0x65): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `etl::impl::cudnn::cudnn_handle::cudnn_handle()':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn12cudnn_handleC2Ev[_ZN3etl4impl5cudnn12cudnn_handleC2Ev]+0x11): undefined reference to `cudnnCreate'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn12cudnn_handleC2Ev[_ZN3etl4impl5cudnn12cudnn_handleC2Ev]+0x43): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `etl::impl::cudnn::cudnn_handle::~cudnn_handle()':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn12cudnn_handleD2Ev[_ZN3etl4impl5cudnn12cudnn_handleD2Ev]+0x10): undefined reference to `cudnnDestroy'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn12cudnn_handleD2Ev[_ZN3etl4impl5cudnn12cudnn_handleD2Ev]+0x4c): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `cudnnTensorStruct* etl::impl::cudnn::create_tensor<etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, (cpp::detail::enabler_t)0>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x1b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x4d): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x145): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x177): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `cudnnTensorStruct* etl::impl::cudnn::create_tensor<etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&, (cpp::detail::enabler_t)0>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x1b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x4d): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x145): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x177): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `void etl::impl::cudnn::activation<etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&, cudnnActivationMode_t)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x53): undefined reference to `cudnnCreateActivationDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x8f): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x1df): undefined reference to `cudnnSetActivationDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x224): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x41f): undefined reference to `cudnnActivationForward'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x464): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x5a5): undefined reference to `cudnnDestroyActivationDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t[_ZN3etl4impl5cudnn10activationIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERS5_EEvOT_OT0_21cudnnActivationMode_t]+0x5ea): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `cudnnTensorStruct* etl::impl::cudnn::create_tensor_flat<etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x1b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x4d): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x12d): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x15f): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `cudnnTensorStruct* etl::impl::cudnn::create_tensor_flat<etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul>&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x1b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x4d): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x12d): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn18create_tensor_flatIRNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEEEEP17cudnnTensorStructOT_]+0x15f): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `void etl::impl::cudnn::bias_batch_mean_2d<etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 1ul>&>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, etl::dyn_matrix_impl<float, (etl::order)0, 1ul>&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18bias_batch_mean_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERNS3_IfLS4_0ELm1EEEEEvOT_OT0_[_ZN3etl4impl5cudnn18bias_batch_mean_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERNS3_IfLS4_0ELm1EEEEEvOT_OT0_]+0xe2): undefined reference to `cudnnConvolutionBackwardBias'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn18bias_batch_mean_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERNS3_IfLS4_0ELm1EEEEEvOT_OT0_[_ZN3etl4impl5cudnn18bias_batch_mean_2dIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEERNS3_IfLS4_0ELm1EEEEEvOT_OT0_]+0x11e): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `cudnnTensorStruct* etl::impl::cudnn::create_tensor_front<etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&, (cpp::detail::enabler_t)0>(etl::dyn_matrix_impl<float, (etl::order)0, 2ul> const&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x1b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x4d): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x139): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn19create_tensor_frontIRKNS_15dyn_matrix_implIfLNS_5orderE0ELm2EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x16b): undefined reference to `cudnnGetErrorString'
> /tmp/mnist_ae-95cfa4.o: In function `cudnnTensorStruct* etl::impl::cudnn::create_tensor<etl::dyn_matrix_impl<float, (etl::order)0, 1ul>&, (cpp::detail::enabler_t)0>(etl::dyn_matrix_impl<float, (etl::order)0, 1ul>&)':
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x1b): undefined reference to `cudnnCreateTensorDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x4d): undefined reference to `cudnnGetErrorString'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x133): undefined reference to `cudnnSetTensor4dDescriptor'
> mnist_ae.cpp:(.text._ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_[_ZN3etl4impl5cudnn13create_tensorIRNS_15dyn_matrix_implIfLNS_5orderE0ELm1EEELN3cpp6detail9enabler_tE0EEEP17cudnnTensorStructOT_]+0x165): undefined reference to `cudnnGetErrorString'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [ae] error 1

What is the problem ? How can I solve it ?
My GPU info are:
![image](https://user-images.githubusercontent.com/26650198/31927586-c1e10b44-b8cf-11e7-9269-34f23d593002.png)

**Comment by wichtounet** [comment]
Hi

In the LDFLAGS, can you add -lcudnn ?

It should be enough.

**Comment by kjleeic** [comment]
Thank you it works!
